# Generated by Django 3.2.12 on 2022-08-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('powertype', models.CharField(max_length=20)),
                ('wings', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
            },
        ),
    ]
