# Generated by Django 3.2.12 on 2022-08-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='Pet',
        ),
    ]
