# Generated by Django 3.2.12 on 2022-08-09 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='wheels',
            new_name='doors',
        ),
    ]
